# Coneccion de sql server
spring:
  datasource:
    url: jdbc:sqlserver://\ASUS\SQL2012;database=DW_SSID_DB
    username: sa
    password: control
    platform: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    database: SQL_SERVER
    show-sql: true
#Port initialize
server:
  port: 8082

